server:
  port: 8003

discovery:
  service-id: chunk-server
  server-host: http://127.0.0.1
  server-port: 8080
  schema: http


swagger:
  config:
    base-package: com.wbu.controller

chunk:
#  linux
#  work-space: /usr/local/server2
#  windows
  work-space: D:/MyDataArea/wfs/chunk-server2