server:
  port: 8001

discovery:
  service-id: chunk-server
  server-host: http://127.0.0.1
  server-port: 8080
  schema: http


swagger:
  config:
    base-package: com.wbu.controller

chunk:
  work-space: D:/MyDataArea/wfs/
